let lista = [

'paz', 'ceu', 'ser', 'ver', 'mae', 'ego', 'bem', 'dom', 'bom', 
'dar', 'ora', 'era', 'elo', 'luz', 'nos', 'reu', 'seu', 'tal', 
'eco', 'rol', 'lua', 'fim', 'dor', 'ato', 'sol', 'pai', 'dia', 
'rua', 'ler', 'voz', 'gay', 'lei', 'voo', 'mau', 'mao', 'des', 
'lar', 'ira', 'som', 'rei', 'boa', 'mes', 'jaz', 'asa', 'amor', 
'fato', 'mito', 'vies', 'voce', 'como', 'caos', 'esmo', 'brio', 
'vide', 'acao', 'sede', 'apos', 'pois', 'vida', 'casa', 'auge', 
'saga', 'medo', 'onus', 'ermo', 'suma', 'vovo', 'mote', 'alem', 
'sina', 'tolo', 'idem', 'urge', 'pela', 'crer', 'apto', 'zelo', 
'veio', 'pude', 'tudo', 'mais', 'ruim', 'amar', 'area', 'rude', 
'coxo', 'para', 'cota', 'soar', 'ater', 'sera', 'fase', 'ente', 
'auto', 'doce', 'tras', 'voga', 'logo', 'onde', 'deus', 'pelo', 
'rima', 'ante', 'cedo', 'jugo', 'alma', 'meio', 'arte', 'meta', 
'cujo', 'sela', 'numa', 'traz', 'sido', 'cela', 'teor', 'noia', 
'face', 'asco', 'nojo', 'isso', 'alvo', 'foco', 'pose', 'sair', 
'base', 'vale', 'odio', 'agir', 'teve', 'alto', 'todo', 'ocio', 
'rito', 'eita', 'irao', 'novo', 'agil', 'alva', 'tese', 'alta', 
'bojo', 'nexo', 'orla', 'sagaz', 'amago', 'negro', 'termo', 
'exito', 'mexer', 'nobre', 'senso', 'afeto', 'algoz', 'etica', 
'plena', 'mutua', 'tenue', 'fazer', 'assim', 'vigor', 'sutil', 
'aquem', 'porem', 'secao', 'fosse', 'sanar', 'poder', 'audaz', 
'ideia', 'cerne', 'inato', 'moral', 'sobre', 'desde', 'muito', 
'justo', 'honra', 'quica', 'torpe', 'sonho', 'razao', 'etnia', 
'futil', 'icone', 'anexo', 'amigo', 'egide', 'tange', 'lapso', 
'haver', 'expor', 'dengo', 'mutuo', 'tempo', 'casal', 'entao', 
'habil', 'seara', 'bocal', 'avido', 'ardil', 'pesar', 'saber', 
'causa', 'graca', 'dizer', 'genro', 'obice', 'posse', 'coser', 
'dever', 'paria', 'brado', 'tenaz', 'prole', 'sendo', 'crivo', 
'comum', 'corja', 'temor', 'detem', 'ainda', 'animo', 'apice', 
'estar', 'ceder', 'ansia', 'xibiu', 'pauta', 'digno', 'assaz', 
'culto', 'mundo', 'atroz', 'fugaz', 'censo', 'gleba', 'forte', 
'vicio', 'vulgo', 'cozer', 'valha', 'denso', 'exceto', 'cinico', 
'idoneo', 'ambito', 'nescio', 'indole', 'mister', 'vereda', 
'apogeu', 'inocuo', 'convem', 'utopia', 'sadico', 'escopo', 
'enfase', 'idiota', 'casual', 'merito', 'alusao', 'hostil', 
'anseio', 'cetico', 'legado', 'hetero', 'pressa', 'gentil', 
'alheio', 'nocivo', 'infame', 'cliche', 'defina', 'paixao', 
'eximio', 'afavel', 'adorno', 'dadiva', 'extase', 'sobrio', 
'larica', 'adesao', 'aferir', 'astuto', 'tambem', 'otario', 
'sessao', 'limiar', 'solene', 'gloria', 'julgar', 'labaro', 
'formal', 'habito', 'apreco', 'embora', 'ensejo', 'impeto', 
'eficaz', 'outrem', 'ocioso', 'jubilo', 'dispor', 'difuso', 
'alento', 'perene', 'nuance', 'faccao', 'escusa', 'exilio', 
'cessao', 'ludico', 'abster', 'ilacao', 'alcada', 'objeto', 
'acesso', 'acento', 'desejo', 'axioma', 'sancao', 'tacito', 
'isento', 'etereo', 'buscar', 'mulher', 'cortes', 'cobica', 
'mazela', 'sisudo', 'penhor', 'eximir', 'avidez', 'receio', 
'vulgar', 'remoto', 'prazer', 'quando', 'fatico', 'sempre', 
'nomade', 'asseio', 'empatia', 'aurelio', 'conjuge', 'embuste', 
'excecao', 'carater', 'efemero', 'prolixo', 'verbete', 'idilico', 
'analogo', 'genuino', 'estoria', 'sublime', 'familia', 'pesames', 
'inferir', 'apatico', 'sucinto', 'acepcao', 'redimir', 'astucia', 
'prodigo', 'cultura', 'audacia', 'estigma', 'recesso', 'virtude', 
'refutar', 'iconico', 'soberba', 'cinismo', 'estavel', 'exortar', 
'morbido', 'trivial', 'mitigar', 'sintese', 'aspecto', 'luxuria', 
'cordial', 'sucesso', 'alegria', 'imputar', 'escoria', 'anatema', 
'emergir', 'ademais', 'candura', 'orgulho', 'deboche', 'excerto', 
'litigio', 'almejar', 'atraves', 'contudo', 'frivolo', 'coragem', 
'saudade', 'oriundo', 'escroto', 'alcunha', 'ambiguo', 'salutar', 
'austero', 'amizade', 'racismo', 'quimera', 'sensato', 'ambicao', 
'excesso', 'relacao', 'erudito', 'imersao', 'fomento', 'modesto', 
'parcial', 'demanda', 'colosso', 'ciencia', 'exotico', 'conciso', 
'piedade', 'volatil', 'notorio', 'bizarro', 'isencao', 'vigente', 
'padecer', 'hibrido', 'auferir', 'intenso', 'inercia', 'emotivo', 
'ansioso', 'sentido', 'despota', 'profano', 'limpido', 'difusao', 
'inerente', 'respeito', 'peculiar', 'denegrir', 'genocida', 
'anuencia', 'deferido', 'equidade', 'prudente', 'iminente', 
'essencia', 'pandemia', 'misogino', 'desgraca', 'invasivo', 
'alienado', 'eminente', 'premissa', 'abstrato', 'extensao', 
'empirico', 'conceito', 'talarico', 'ardiloso', 'ascensao', 
'rapariga', 'reiterar', 'lascivia', 'devaneio', 'relativo', 
'prodigio', 'passivel', 'conserto', 'gratidao', 'analogia', 
'insercao', 'modestia', 'apologia', 'ativista', 'remissao', 
'inospito', 'destarte', 'mediocre', 'despeito', 'fomentar', 
'monotono', 'inefavel', 'respaldo', 'retorica', 'concerne', 
'alicerce', 'sinonimo', 'proceder', 'metodico', 'primazia', 
'perfidia', 'historia', 'rechacar', 'portanto', 'complexo', 
'demagogo', 'consiste', 'criterio', 'notivago', 'espectro', 
'distinto', 'sucumbir', 'amalgama', 'abnegado', 'desfecho', 
'paradoxo', 'suscitar', 'singular', 'escarnio', 'contexto', 
'processo', 'comunhao', 'elegivel', 'objetivo', 'vocabulo', 
'refletir', 'impavido', 'maestria', 'obstante', 'problema', 
'endemico', 'designio', 'juridico', 'solicito', 'instigar', 
'incrivel', 'redencao', 'epifania', 'mediante', 'paralelo', 
'insipido', 'imanente', 'preceito', 'resoluto', 'generico', 
'perspicaz', 'reciproco', 'concessao', 'impressao', 'escrupulo', 
'superfluo', 'retificar', 'paradigma', 'dicotomia', 'proposito', 
'presuncao', 'concepcao', 'hipocrita', 'ratificar', 'implicito', 
'plenitude', 'essencial', 'hegemonia', 'corolario', 'incidente', 
'esdruxulo', 'altruismo', 'vagabundo', 'altruista', 'hermetico', 
'aleatorio', 'esperanca', 'promiscuo', 'persuadir', 'confianca', 
'deliberar', 'sapiencia', 'indelevel', 'demasiado', 'diligente', 
'mesquinho', 'impetuoso', 'descricao', 'regozijar', 'resignado', 
'inusitado', 'eminencia', 'compaixao', 'prudencia', 'pretensao', 
'discricao', 'analitico', 'explicito', 'ordinario', 'percepcao', 
'exequivel', 'subjetivo', 'nostalgia', 'autonomia', 'autoctone', 
'companhia', 'resolucao', 'fidedigno', 'desdenhar', 'dissensao', 
'expressao', 'constante', 'supressao', 'taciturno', 'imparcial', 
'autentico', 'paciencia', 'ignorante', 'arrogante', 'outrossim', 
'execravel', 'desumilde', 'discorrer', 'restricao', 'consoante', 
'obstinado', 'jactancia', 'arcabouco', 'cognitivo', 'eloquente', 
'adjacente', 'instancia', 'interesse', 'limitrofe', 'sintetico', 
'iminencia', 'submissao', 'pressagio', 'relevante', 'irascivel', 
'empecilho', 'excelente', 'liberdade', 'ludibriar', 'humildade', 
'aquisicao', 'plausivel', 'ambicioso', 'conviccao', 'primicias', 
'dicionario', 'intrinseco', 'prescindir', 'presuncoso', 
'diligencia', 'corroborar', 'intemperie', 'detrimento', 
'maturidade', 'parcimonia', 'referencia', 'inspiracao', 
'inexoravel', 'pragmatico', 'prepotente', 'incipiente', 
'disruptivo', 'sororidade', 'serenidade', 'arbitrario', 
'indulgente', 'auspicioso', 'iniquidade', 'pertinente', 
'sagacidade', 'resignacao', 'hipocrisia', 'preconizar', 
'precedente', 'vislumbrar', 'incidencia', 'lisonjeado', 
'suscetivel', 'entretanto', 'disposicao', 'excentrico', 
'subestimar', 'preliminar', 'tribulacao', 'fleumatico', 
'depreender', 'anacronico', 'equivocado', 'escrutinio', 
'retrogrado', 'indolencia', 'excelencia', 'ingerencia', 
'democracia', 'infortunio', 'compassivo', 'contemplar', 
'importante', 'pejorativo', 'restringir', 'sintetizar', 
'proposicao', 'primordial', 'signatario', 'conjuntura', 
'subjacente', 'coercitivo', 'intrinseca', 'dissolucao', 
'itinerario', 'finalidade', 'esplendido', 'alteridade', 
'pecuniaria', 'subversivo', 'espontaneo', 'designacao', 
'transeunte', 'necessario', 'constancia', 'sarcastico', 
'pusilanime', 'privilegio', 'idoneidade', 'desprovido', 
'verossimil', 'pernostico', 'exacerbado', 'felicidade', 
'relevancia', 'disciplina', 'divergente', 'inferencia', 
'pernicioso', 'disseminar', 'satisfacao', 'reverberar', 
'meticuloso', 'esporadico', 'influencia', 'militancia', 
'retumbante', 'consolidar', 'fornicacao', 'significado', 
'perspectiva', 'resiliencia', 'dissimulado', 'vicissitude', 
'complacente', 'contundente', 'peremptorio', 'comorbidade', 
'compreensao', 'perspicacia', 'expectativa', 'pressuposto', 
'beneplacito', 'subterfugio', 'preconceito', 'experiencia', 
'indiferente', 'consonancia', 'pretensioso', 'transcender', 
'imensuravel', 'contingente', 'intensidade', 'proeminente', 
'beligerante', 'necessidade', 'superficial', 'concernente', 
'benignidade', 'contencioso', 'inenarravel', 'animosidade', 
'intervencao', 'incumbencia', 'vocabulario', 'antagonismo', 
'cumprimento', 'resistencia', 'indiferenca', 'reivindicar', 
'compreender', 'supracitado', 'subsequente', 'estereotipo', 
'integridade', 'diversidade', 'ambiguidade', 'deliberacao', 
'especulacao', 'indulgencia', 'proveniente', 'divergencia', 
'elucubracao', 'indubitavel', 'austeridade', 'prognostico', 
'importancia', 'heterogeneo', 'tergiversar', 'benevolente', 
'displicente', 'negligencia', 'identificar', 'oportunista', 
'estabelecer', 'conveniente', 'redundancia', 'consciencia', 
'congruencia', 'discriminar', 'pragmatismo', 'substantivo', 
'excepcional', 'providencia', 'admoestacao', 'conferencia', 
'facultativo', 'sistematico', 'compulsorio', 'comprimento', 
'verborragia', 'interseccao', 'subordinado', 'intelectual', 
'melancolico', 'contradicao', 'relativizar', 'generalizar', 
'desenvolver', 'substancial', 'honestidade', 'dificuldade', 
'retificacao', 'conservador', 'procedencia', 'autoritario', 
'amabilidade', 'determinado', 'antagonista', 'perseveranca', 
'condolencias', 'remanescente', 'prerrogativa', 'extrovertido', 
'complacencia', 'procrastinar', 'discrepancia', 'determinacao', 
'independente', 'consequencia', 'intermitente', 'conveniencia', 
'benevolencia', 'compartilhar', 'eclesiastico', 'contingencia', 
'transgressao', 'felicitacoes', 'consideracao', 'concomitante', 
'convergencia', 'cordialidade', 'conhecimento', 'cumplicidade', 
'convencional', 'subsistencia', 'disseminacao', 'proselitismo', 
'sistematizar', 'coincidencia', 'complexidade', 'prescindivel', 
'controversia', 'imprevisivel', 'impertinente', 'inverossimil', 
'escatologico', 'displicencia', 'interlocutor', 'ninfomaniaco', 
'libertinagem', 'conformidade', 'proporcionar', 'intempestivo', 
'maledicencia', 'extemporaneo', 'fraternidade', 'intolerancia', 
'resplandecer', 'perseverante', 'misericordia', 'estabilidade', 
'mediocridade', 'persistencia', 'coexistencia', 'maquiavelico', 
'circunspecto', 'preeminencia', 'aquiescencia', 'hermeneutica', 
'protagonista', 'complementar', 'parcialmente', 'proeminencia', 
'introvertido', 'consolidacao', 'oportunidade', 'constituicao', 
'destinatario', 'escarnecedor', 'deslumbrante', 'estigmatizar', 
'consistencia', 'parcialidade', 'entendimento', 'interessante', 
'caracterizar', 'incircunciso', 'procedimento', 'generosidade', 
'condicionado', 'circuncidado', 'enclausurado', 'superestimar', 
'fragmentacao', 'literalmente', 'desenvoltura', 'proficiencia', 
'prosperidade', 'depreciativo', 'legitimidade', 'simplicidade', 
'profissional', 'incolumidade', 'ininterrupto', 'sobremaneira', 
'inescrutavel', 'beneficencia', 'reciprocidade', 'contemporaneo', 
'inconveniente', 'heterossexual', 'circunstancia', 'discernimento', 
'solidariedade', 'promiscuidade', 'ressignificar', 'intransigente', 
'credibilidade', 'discriminacao', 'transcendente', 'aprovisionado', 
'epistemologia', 'contrapartida', 'assintomatico', 'comprobatorio', 
'perpendicular', 'incongruencia', 'reminiscencia', 'ressentimento', 
'estereotipado', 'possibilidade', 'recenseamento', 'intermediario', 
'veementemente', 'preponderante', 'indispensavel', 'subjetividade', 
'hodiernamente', 'singularidade', 'subserviencia', 'longanimidade', 
'convalescenca', 'pormenorizado', 'transformacao', 'autenticidade', 
'independencia', 'incontinencia', 'instabilidade', 'superveniente', 
'sensibilidade', 'introspectivo', 'reivindicacao', 'elegibilidade', 
'superestimado', 'contraditorio', 'indissociavel', 'multifacetado', 
'eventualmente', 'latifundiario', 'recalcitrante', 'desmistificar', 
'incredulidade', 'quintessencia', 'inconsequente', 'sobressalente', 
'ininteligivel', 'inescrupuloso', 'comportamento', 'personalidade', 
'indescritivel', 'integralmente', 'implementacao', 'monossilabico', 
'homogeneidade', 'magnificencia', 'provavelmente', 'precipuamente', 
'peculiaridade', 'circunscricao', 'consentimento', 'incondicional', 
'convalescente', 'remanejamento', 'serendipidade', 'contentamento', 
'consciencioso', 'correlacionar', 'arrefecimento', 'incandescente', 
'predisposicao', 'versatilidade', 'conscientizar', 'desnecessario', 
'irresponsavel', 'supersticioso', 'indeterminado', 'imperceptivel', 
'representacao', 'especificacao', 'identificacao', 'reconciliacao', 
'incognoscivel', 'ressarcimento', 'receptividade', 'monocromatico', 
'imprescindivel', 'condescendente', 'idiossincrasia', 'caracteristica', 
'concupiscencia', 'extraordinario', 'demasiadamente', 'intercorrencia', 
'irrepreensivel', 'consubstanciar', 'pronta-entrega', 'incomensuravel', 
'discricionario', 'preponderancia', 'arbitrariedade', 'especificidade', 
'posteriormente', 'imprescritivel', 'intransponivel', 'contextualizar', 
'empreendimento', 'ancestralidade', 'entretenimento', 'transcendental', 
'paulatinamente', 'infraestrutura', 'relacionamento', 'arrependimento', 
'revolucionario', 'imparcialidade', 'superveniencia', 'sobrecarregado', 
'atenciosamente', 'transcendencia', 'periodicamente', 'transfiguracao', 
'reconhecimento', 'democratizacao', 'insignificante', 'diligentemente', 
'inconsistencia', 'personificacao', 'despretensioso', 'impessoalidade', 
'socioambiental', 'espontaneidade', 'funcionalidade', 'intransigencia', 
'aplicabilidade', 'desprendimento', 'procrastinacao', 'principalmente', 
'potencialidade', 'estelionatario', 'procrastinador', 'estratificacao', 
'licenciosidade', 'extraordinaria', 'prestatividade', 'excentricidade', 
'inconveniencia', 'dissolutamente', 'congratulacoes', 'pusilanimidade', 
'exequibilidade', 'epistemologico', 'insubstituivel', 'individualismo', 
'biodiversidade', 'resplandecente', 'jurisprudencia', 'abundantemente', 
'coercitividade', 'disponibilizar', 'plausibilidade', 'acessibilidade', 
'internalizacao', 'credenciamento', 'papibaquigrafo', 'constantemente', 
'exclusivamente', 'perfeccionista', 'multiplicidade', 'aleatoriamente', 
'impressionante', 'questionamento', 'implicitamente', 'grandiloquente', 
'esclarecimento', 'minuciosamente', 'permissividade', 'frequentemente', 
'indiscriminado', 'intermunicipal', 'concessionaria'

];

//module.exports = lista;
